apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  clusterIP: 10.102.4.3
  selector:
    app: sample-app
  ports:
  - port: 8080
    name: http-port
    protocol: TCP
    targetPort: 80
