apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-binary-webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: sample-configmap-binary
